### ISSUE TITLE
0.1 Milestone

### ISSUE THREAD

**Issue by jc4p** [jc4p/ReactiveArena#1]
# Version 0.1

Goal: Bare minimal functioning read-only channel/blocks navigator. 
- [ ] Grid view that can handle all types of blocks (images, URLs, links to other channels, etc)
- [ ] [Tapping on a block should lead the appropriate action](https://github.com/jc4p/ReactiveArena/issues/2)
- [ ] API consumer for all the applicable read-only [channel API calls](https://dev.are.na/documentation/channels)
- [ ] Ability to manually type in a channel name

I'm _totally_ okay with hardcoding a base channel for it to load on start-up, I'm thinking https://www.are.na/lukas-wp/meme-metachannel -- but a user should still be able to hit a button and type in a different base channel name without compiling the app themselves.
